# -*- mode: snippet -*-
# name: makefile
# key: makefile
# --
`(file-name-nondirectory (file-name-sans-extension (buffer-file-name)))`: `(file-name-nondirectory (buffer-file-name))`
			 g++ -Wall -g `(file-name-nondirectory (buffer-file-name))` -o	`(file-name-nondirectory (file-name-sans-extension (buffer-file-name)))`

